---
- hosts: local
  tasks:
    - include_vars: vault_vars.yml
    - include_vars: vars.yml

    - debug: var=registry_url

    - name: Get ECR Token
      shell: "{{ playbook_dir }}/.ecr_login.sh"

    - name: Remove image
      docker_image:
        state: absent
        name: "{{ registry_url }}"

    - name: Build an image and push it to a private repo
      docker_image:
        path: "{{ playbook_dir }}/journals_code"
        name: "{{ registry_url }}"
        push: yes