---
- hosts: local
  tasks:
    - include_vars: vault_vars.yml
    - include_vars: vars.yml

    # Gather facts about all running ec2 instances with a tag of Name:Example
    - ec2_remote_facts:
        region: "{{ aws_region }}"
        filters:
          instance-state-name: running
          "tag:Name": journals-swarm-Manager
      register: ec2_facts

    - debug: var=ec2_facts.instances.0.public_ip_address

    - blockinfile:
        path: "{{ playbook_dir }}/.inventory"
        create: yes
        block: |
          [swarm-manager]
          manager ansible_host={{ ec2_facts.instances.0.public_ip_address}} ansible_user=docker
